### ISSUE TITLE
[Feature Request] Larger Pictograms for nodes in graph and line wrap for Titles in Graphs

### ISSUE THREAD

**Issue by StoltHD** [mkalus/segrada#56]
Would it be possible to ask for bigger pictograms in the Graph View?

I would like to use Logos for different Companies to better visualize them...

It would also be great if you could add Line Wrapping for the Title in Graph View...
Reason for this is that when you have Nodes with long Names, i.e. a Government Office og a Company or the full name for a Museum/Library, the Title Text will often cover Titles of other Nodes...

It would also be great if we could chose to use the Description of Relations as descriptors for the Relations in the Graph View, instead of the Relation Type.

**Comment by mkalus** [comment]
Line breaks have been introduced in vis.js, so implemented them.

Regading the other wishes, I may take a look if there is a time contingent left on the current project.

**Comment by mkalus** [comment]
I am looking into the issue with small pictograms. You are right.

Currently, pictograms are created as 24x24px images, but in the graph they are rendered as 50x50px pictures. It might help to create 48x48px images in order to render pictograms nicely on high resolution monitors (i.e. Mac) anyway and I guess nowadways, the disk size used by pictograms is not a problem any more.

The only downside is, that you will have to upload your pictograms again...

**Comment by mkalus** [comment]
Also a TODO for me: support uploading SVG images as pictograms.

**Comment by mkalus** [comment]
Ok, implemented changes and scheduled for next release v0.5.4.
